[package]
name = "codeopen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
home = "0.5.3"
serde = {version="1.0.130", features=["derive"]}
structopt = "0.3.13"